export const ALL_BOOKS_REQUEST = "ALL_BOOKS_REQUEST";
export const ALL_BOOKS_SUCCESS = "ALL_BOOKS_SUCCESS";
export const ALL_BOOKS_FAIL = "ALL_BOOKS_FAIL";

export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";

export const UPDATE_BOOK_REQUEST = "UPDATE_BOOKS_REQUEST";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOKS_SUCCESS";
export const UPDATE_BOOK_FAIL = "UPDATE_BOOKS_FAIL";

export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

